modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "aewireless"
version = "${version}"
displayName = "AE Wireless"
authors = "xiaopiao"
description = 'this is a ae wireless mod'
#logoFile = ""

[[mods.resourcePacks]]
file="1.zip"

[[dependencies.aewireless]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aewireless]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aewireless]]
modId = "ae2"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "aewireless.mixins.json"
